### ISSUE TITLE
TableViewNotFound

### ISSUE THREAD

**Issue by lic1227** [PerfAssist/PA_CoroutineTracker#4]
TableViewNotFound

**Comment by foxnoodles** [comment]
same, I've downloaded the table view and common scripts from other assets but it still doesn't work properly. the table view is blank. there are no coroutine names. Can u fix this cuz this thing is kinda useful.

**Comment by virtual-serenity** [comment]
@lic1227 @foxnoodles 

For your patience, this repository has been merged into https://github.com/GameBuildingBlocks/PerfAssist


For your issue, it's because you didn't get the submodule (use "git submodule update...")

**Comment by foxnoodles** [comment]
Well I've downloaded it directly(zip), never pulled it... it should've work out of the box.
